### ISSUE TITLE
organize in module hierarchy

### ISSUE THREAD

**Issue by gittywithexcitement** [black0range/BufferedSocket#1]
Your library looks interesting and I considered using it, however the code isn't organized idiomatically. You've placed all of your modules in the top level namespace. I don't think this is how the module namespace is supposed to be used; it 'pollutes' the top level namespace and renders it unusable by other packages. I instead recommend that you organize your modules like this, for example:

Network.BufferedSocket
Network.BufferedSocket.Core
Network.BufferedSocket.Reader
Network.BufferedSocket.Writer

or some other scheme

**Comment by t-more** [comment]
Hello! Fun that somebody took interest in this! 
And yes, you are absolutely right; I will fix this today.

**Comment by t-more** [comment]
All the changes you proposed are implemented! https://hackage.haskell.org/package/BufferedSocket-0.2.0.0

Thanks for showing interest in the package, If you find anything else you wonder about / want to change, Do not be afraid to say so.
